INFO - 2024-11-27 01:14:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-11-27 01:14:12 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'auditoria_capas', 3306, '', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `id_user...', Array, false)
#4 D:\laragon\www\capas.com\app\Models\AuthModel.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\app\Controllers\AuthController.php(43): App\Models\AuthModel->authenticate('orlando.ramos@d...', 'Dart123')
#6 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `id_user...', Array, false)
#3 D:\laragon\www\capas.com\app\Models\AuthModel.php(30): CodeIgniter\Database\BaseBuilder->get()
#4 D:\laragon\www\capas.com\app\Controllers\AuthController.php(43): App\Models\AuthModel->authenticate('orlando.ramos@d...', 'Dart123')
#5 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AuthController->login()
#6 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-11-27 01:14:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: POST, Route: auth/login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `id_user`, `email`, `name`, `firstName`, `lastName`, `status`, `password`, `fk_role`
FROM `users`
WHERE `email` = :email:
AND `status` = :status:', [...], false)
 3 APPPATH\Models\AuthModel.php(30): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\AuthController.php(43): App\Models\AuthModel->authenticate('orlando.ramos@dart.biz', 'Dart123')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-27 01:14:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:14:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:14:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:14:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:14:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:14:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:41:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:42:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:42:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:42:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:42:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:42:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:43:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:44:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:44:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:44:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:45:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:46:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:47:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:47:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:47:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:47:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-11-27 01:54:40 --> mysqli_sql_exception: Unknown column 'follow_up.linea' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `audit`....', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `audit`....')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `audit`....')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`....', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\app\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', Array)
#6 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
#7 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-11-27 01:54:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'follow_up.linea' in 'field list'
[Method: GET, Route: accions/getVerificaciones/9]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = :audit.id_audit:
AND `audit`.`status` = :audit.status:', [...], false)
 2 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', [])
 4 APPPATH\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-27 01:54:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'follow_up.linea' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = :audit.id_audit:
AND `audit`.`status` = :audit.status:', [...], false)
 4 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', [])
 6 APPPATH\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-27 01:54:40 --> [Caused by] mysqli_sql_exception: Unknown column 'follow_up.linea' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = :audit.id_audit:
AND `audit`.`status` = :audit.status:', [...], false)
 5 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', [])
 7 APPPATH\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-27 01:54:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:54:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:56:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:56:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:56:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:56:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 01:56:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:01:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:01:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:02:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:02:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:02:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:03:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:07:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:17:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:17:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:17:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:17:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-27 02:17:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-11-27 02:17:40 --> mysqli_sql_exception: Unknown column 'follow_up.linea' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `audit`....', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `audit`....')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `audit`....')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`....', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\app\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', Array)
#6 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
#7 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-11-27 02:17:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'follow_up.linea' in 'field list'
[Method: GET, Route: accions/getVerificaciones/9]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = :audit.id_audit:
AND `audit`.`status` = :audit.status:', [...], false)
 2 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', [])
 4 APPPATH\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-27 02:17:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'follow_up.linea' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = :audit.id_audit:
AND `audit`.`status` = :audit.status:', [...], false)
 4 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', [])
 6 APPPATH\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-27 02:17:40 --> [Caused by] mysqli_sql_exception: Unknown column 'follow_up.linea' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = \'9\'
AND `audit`.`status` = 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `audit`.`id_audit`, `audit`.`id_supervisor`, `reviewer`.`email` AS `reviewer_email`, `answers`.`answer`, `actions`.`action_description`, `actions`.`evidence_accion`, `follow_up`.`linea`, `follow_up`.`follow_up`, `follow_up`.`is_resolved`
FROM `audit`
JOIN `users` AS `auditor` ON `auditor`.`id_user` = `audit`.`fk_auditor`
JOIN `users` AS `reviewer` ON `reviewer`.`id_user` = `audit`.`reviewed_by`
JOIN `questions` ON `audit`.`id_audit` = `questions`.`fk_audit`
JOIN `answers` ON `answers`.`fk_question` = `questions`.`id_question`
JOIN `actions` ON `actions`.`fk_answer` = `answers`.`id_answer`
JOIN `follow_up` ON `follow_up`.`fk_accions` = `actions`.`id_actions`
WHERE `audit`.`id_audit` = :audit.id_audit:
AND `audit`.`status` = :audit.status:', [...], false)
 5 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Models\AuditModel.php(95): CodeIgniter\Model->__call('get', [])
 7 APPPATH\Controllers\AccionsController.php(173): App\Models\AuditModel->getAuditVerification('9')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getVerificaciones('9')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
