ERROR - 2024-10-22 17:42:17 --> mysqli_sql_exception: Not unique table/alias: 'answers' in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `actions...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capas.com\app\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', Array)
#6 C:\laragon\www\capas.com\app\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
#7 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-10-22 17:42:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Not unique table/alias: 'answers'
[Method: GET, Route: user/takenActions/52]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 2 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 4 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 17:42:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Not unique table/alias: 'answers'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 4 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 6 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 17:42:17 --> [Caused by] mysqli_sql_exception: Not unique table/alias: 'answers'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 5 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 7 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-22 17:42:28 --> mysqli_sql_exception: Not unique table/alias: 'answers' in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `actions...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capas.com\app\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', Array)
#6 C:\laragon\www\capas.com\app\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
#7 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-10-22 17:42:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Not unique table/alias: 'answers'
[Method: GET, Route: user/takenActions/52]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 2 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 4 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 17:42:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Not unique table/alias: 'answers'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 4 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 6 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 17:42:28 --> [Caused by] mysqli_sql_exception: Not unique table/alias: 'answers'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 5 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 7 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-22 17:43:33 --> mysqli_sql_exception: Not unique table/alias: 'answers' in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `actions...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capas.com\app\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', Array)
#6 C:\laragon\www\capas.com\app\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
#7 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-10-22 17:43:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Not unique table/alias: 'answers'
[Method: GET, Route: user/takenActions/52]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 2 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 4 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 17:43:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Not unique table/alias: 'answers'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 4 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 6 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 17:43:33 --> [Caused by] mysqli_sql_exception: Not unique table/alias: 'answers'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = \'52\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `actions`.`id_action`, `actions`.`action`, `actions`.`responsable`, `actions`.`date`, `actions`.`evidence`, `answers`.`is_complete`
FROM `answers`
JOIN `actions` ON `actions`.`fk_audit` = `audit`.`id_audit`
JOIN `answers` ON `answers`.`id_answer` = `actions`.`fk_answer`
WHERE `audit`.`id_audit` = :audit.id_audit:', [...], false)
 5 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Models\AnswersModel.php(33): CodeIgniter\Model->__call('get', [])
 7 APPPATH\Controllers\UserController.php(22): App\Models\AnswersModel->getAcciones('52')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->takenActions('52')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-22 19:52:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-22 19:53:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-22 19:53:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-22 19:53:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-10-22 19:55:01 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "accions/add_questions.php"
[Method: GET, Route: accions/addquestions]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('accions/add_questions.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('accions/add_questions', [], true)
 3 APPPATH\Controllers\AccionsController.php(187): view('accions/add_questions')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->addquestions()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-22 19:55:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-10-22 19:55:28 --> mysqli_sql_exception: Unknown column 'questions.create_for' in 'field list' in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `questio...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questio...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questio...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questio...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\capas.com\app\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\capas.com\app\Controllers\AccionsController.php(105): App\Models\QuestionsModel->showAllQuestions()
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-22 19:55:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'questions.create_for' in 'field list'
[Method: GET, Route: accions/showQuestion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(105): App\Models\QuestionsModel->showAllQuestions()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 19:55:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'questions.create_for' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(105): App\Models\QuestionsModel->showAllQuestions()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-22 19:55:28 --> [Caused by] mysqli_sql_exception: Unknown column 'questions.create_for' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(105): App\Models\QuestionsModel->showAllQuestions()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-22 19:55:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-22 21:19:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-22 21:19:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-10-22 21:21:36 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "dashboard.php"
[Method: GET, Route: accions/dashboard]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('dashboard.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('dashboard', [], true)
 3 APPPATH\Controllers\AccionsController.php(18): view('dashboard')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->dashboard()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
