INFO - 2024-10-23 00:35:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 00:36:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:07:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:08:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:08:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:08:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:09:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:09:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:10:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:10:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:10:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:12:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-10-23 01:12:55 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:12:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:12:55 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:12:55 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:13:39 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:13:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:13:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:13:39 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:13:56 --> mysqli_sql_exception: Unknown column 'questions.create_for' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `questio...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questio...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questio...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questio...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:13:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'questions.create_for' in 'field list'
[Method: GET, Route: accions/showQuestion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:13:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'questions.create_for' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:13:56 --> [Caused by] mysqli_sql_exception: Unknown column 'questions.create_for' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:14:22 --> mysqli_sql_exception: Unknown column 'questions.create_for' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `questio...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questio...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questio...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questio...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:14:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'questions.create_for' in 'field list'
[Method: GET, Route: accions/showQuestion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:14:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'questions.create_for' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:14:22 --> [Caused by] mysqli_sql_exception: Unknown column 'questions.create_for' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = 1
ORDER BY `category`.`category` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `questions`.`id_question`, `questions`.`question`, `questions`.`create_for`, `questions`.`status`, `source`.`source`, `category`.`category`
FROM `questions`
JOIN `category` ON `questions`.`fk_category` = `category`.`id_category`
JOIN `source` ON `questions`.`fk_source` = `source`.`id_source`
WHERE `questions`.`status` = :questions.status:
ORDER BY `category`.`category` ASC', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(57): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(108): App\Models\QuestionsModel->showAllQuestions()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->showQuestion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:18:21 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:18:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:18:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:18:21 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:18:54 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:18:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:18:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:18:54 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:19:02 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:19:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:19:02 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:19:02 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:19:09 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:19:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:19:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:19:09 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 01:19:27 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:19:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:19:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:19:27 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-23 01:26:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-10-23 01:28:08 --> mysqli_sql_exception: Unknown column 'category.category' in 'field list' in D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `categor...', 0)
#1 D:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `categor...')
#2 D:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `categor...')
#3 D:\laragon\www\capas.com\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#4 D:\laragon\www\capas.com\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\laragon\www\capas.com\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\laragon\www\capas.com\app\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
#7 D:\laragon\www\capas.com\app\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
#8 D:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
#9 D:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 D:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 01:28:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
[Method: GET, Route: accions/getAudit/7]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:28:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 01:28:08 --> [Caused by] mysqli_sql_exception: Unknown column 'category.category' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `category`.`category`, `questions`.`question`, `questions`.`create_at`, `source`.`source`
FROM `questions`
JOIN `source` ON `source`.`id_source` = `questions`.`fk_source`
JOIN `category` ON `category`.`id_category` = `questions`.`fk_category`
WHERE `questions`.`fk_audit` = :questions.fk_audit:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\QuestionsModel.php(36): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\AccionsController.php(72): App\Models\QuestionsModel->getAudit('7')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->getAudit('7')
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-23 01:29:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:30:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:31:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:31:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:31:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:31:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 01:34:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 14:55:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 14:55:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 14:55:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 14:56:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-10-23 16:01:32 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-10-23 16:01:32 --> 220 smtp.gmail.com ESMTP 006d021491bc7-5ebb79d8d6dsm1835122eaf.1 - gsmtp

hello: 250-smtp.gmail.com at your service, [136.226.1.35]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 006d021491bc7-5ebb79d8d6dsm1835122eaf.1 - gsmtp

ERROR - 2024-10-23 16:01:32 --> No se pudo enviar el correo de verificación a usuario1.apellido1@dart.biz
ERROR - 2024-10-23 16:02:34 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto in C:\laragon\www\capas.com\system\Email\Email.php:1896
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): SS...', 'C:\\laragon\\www\\...', 1896)
#1 C:\laragon\www\capas.com\system\Email\Email.php(1896): fsockopen('ssl://smtp.gmai...', 465, NULL, NULL, 5)
#2 C:\laragon\www\capas.com\system\Email\Email.php(1809): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\laragon\www\capas.com\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\laragon\www\capas.com\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#5 C:\laragon\www\capas.com\app\Controllers\AdminController.php(97): CodeIgniter\Email\Email->send()
#6 C:\laragon\www\capas.com\app\Controllers\AdminController.php(77): App\Controllers\AdminController->sendVerificationEmail('username2.apell...', 'fe8e2d83a4e3ca3...')
#7 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2024-10-23 16:02:34 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-10-23 16:02:34 --> 
ERROR - 2024-10-23 16:02:34 --> No se pudo enviar el correo de verificación a username2.apellido2@dart.biz
ERROR - 2024-10-23 16:03:08 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto in C:\laragon\www\capas.com\system\Email\Email.php:1896
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): SS...', 'C:\\laragon\\www\\...', 1896)
#1 C:\laragon\www\capas.com\system\Email\Email.php(1896): fsockopen('ssl://smtp.gmai...', 465, NULL, NULL, 5)
#2 C:\laragon\www\capas.com\system\Email\Email.php(1809): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\laragon\www\capas.com\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\laragon\www\capas.com\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#5 C:\laragon\www\capas.com\app\Controllers\AdminController.php(97): CodeIgniter\Email\Email->send()
#6 C:\laragon\www\capas.com\app\Controllers\AdminController.php(77): App\Controllers\AdminController->sendVerificationEmail('username3.apell...', '95e018067875240...')
#7 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2024-10-23 16:03:08 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-10-23 16:03:08 --> 
ERROR - 2024-10-23 16:03:08 --> No se pudo enviar el correo de verificación a username3.apellido3@dart.biz
ERROR - 2024-10-23 16:04:06 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto in C:\laragon\www\capas.com\system\Email\Email.php:1896
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): SS...', 'C:\\laragon\\www\\...', 1896)
#1 C:\laragon\www\capas.com\system\Email\Email.php(1896): fsockopen('ssl://smtp.gmai...', 465, NULL, NULL, 5)
#2 C:\laragon\www\capas.com\system\Email\Email.php(1809): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\laragon\www\capas.com\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\laragon\www\capas.com\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#5 C:\laragon\www\capas.com\app\Controllers\AdminController.php(97): CodeIgniter\Email\Email->send()
#6 C:\laragon\www\capas.com\app\Controllers\AdminController.php(77): App\Controllers\AdminController->sendVerificationEmail('username4.apell...', '26c4a0807195859...')
#7 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2024-10-23 16:04:06 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-10-23 16:04:06 --> 
ERROR - 2024-10-23 16:04:06 --> No se pudo enviar el correo de verificación a username4.apellido4@dart.biz
ERROR - 2024-10-23 16:04:53 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-10-23 16:04:53 --> 220 smtp.gmail.com ESMTP 46e09a7af769-7182ec038cesm1717758a34.72 - gsmtp

hello: 250-smtp.gmail.com at your service, [136.226.1.26]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 46e09a7af769-7182ec038cesm1717758a34.72 - gsmtp

ERROR - 2024-10-23 16:04:53 --> No se pudo enviar el correo de verificación a username5.apellido5@dart.biz
CRITICAL - 2024-10-23 16:11:22 --> Error: Call to a member function listErrors() on null
[Method: POST, Route: admin/insertData]
in APPPATH\Controllers\AdminController.php on line 95.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:11:42 --> Error: Call to a member function listErrors() on null
[Method: POST, Route: admin/insertData]
in APPPATH\Controllers\AdminController.php on line 95.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:16:46 --> Error: Call to a member function listErrors() on null
[Method: POST, Route: admin/insertData]
in APPPATH\Controllers\AdminController.php on line 108.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:16:49 --> Error: Call to a member function listErrors() on null
[Method: POST, Route: admin/insertData]
in APPPATH\Controllers\AdminController.php on line 108.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:16:53 --> Error: Call to a member function listErrors() on null
[Method: POST, Route: admin/insertData]
in APPPATH\Controllers\AdminController.php on line 108.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:17:40 --> Error: Call to a member function listErrors() on null
[Method: POST, Route: admin/insertData]
in APPPATH\Controllers\AdminController.php on line 108.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 16:22:09 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`users`, CONSTRAINT `fk_department` FOREIGN KEY (`fk_department`) REFERENCES `department` (`id_department`)) in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capas.com\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capas.com\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capas.com\app\Models\AdminModel.php(33): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capas.com\app\Controllers\AdminController.php(73): App\Models\AdminModel->insertUser(Array)
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
#10 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
#11 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-10-23 16:22:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`users`, CONSTRAINT `fk_department` FOREIGN KEY (`fk_department`) REFERENCES `department` (`id_department`))
[Method: POST, Route: admin/insertData]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (:email:, :name:, :firstName:, :lastName:, :password:, :fk_department:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AdminModel.php(33): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\AdminController.php(73): App\Models\AdminModel->insertUser([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:22:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`users`, CONSTRAINT `fk_department` FOREIGN KEY (`fk_department`) REFERENCES `department` (`id_department`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (\'\', \'\', \'\', \'\', \'$2y$10$0S9FmRL0CAr4tNUptnAFremZKk5x5965IsVJhuWVRhgbR/ia/wk.a\', \'Seleccione un departamento\', \'2024-10-23 16:22:09\', \'2024-10-23 16:22:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (\'\', \'\', \'\', \'\', \'$2y$10$0S9FmRL0CAr4tNUptnAFremZKk5x5965IsVJhuWVRhgbR/ia/wk.a\', \'Seleccione un departamento\', \'2024-10-23 16:22:09\', \'2024-10-23 16:22:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (:email:, :name:, :firstName:, :lastName:, :password:, :fk_department:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AdminModel.php(33): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\AdminController.php(73): App\Models\AdminModel->insertUser([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 16:22:09 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`users`, CONSTRAINT `fk_department` FOREIGN KEY (`fk_department`) REFERENCES `department` (`id_department`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (\'\', \'\', \'\', \'\', \'$2y$10$0S9FmRL0CAr4tNUptnAFremZKk5x5965IsVJhuWVRhgbR/ia/wk.a\', \'Seleccione un departamento\', \'2024-10-23 16:22:09\', \'2024-10-23 16:22:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (\'\', \'\', \'\', \'\', \'$2y$10$0S9FmRL0CAr4tNUptnAFremZKk5x5965IsVJhuWVRhgbR/ia/wk.a\', \'Seleccione un departamento\', \'2024-10-23 16:22:09\', \'2024-10-23 16:22:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (\'\', \'\', \'\', \'\', \'$2y$10$0S9FmRL0CAr4tNUptnAFremZKk5x5965IsVJhuWVRhgbR/ia/wk.a\', \'Seleccione un departamento\', \'2024-10-23 16:22:09\', \'2024-10-23 16:22:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `name`, `firstName`, `lastName`, `password`, `fk_department`, `created_at`, `updated_at`) VALUES (:email:, :name:, :firstName:, :lastName:, :password:, :fk_department:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AdminModel.php(33): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\AdminController.php(73): App\Models\AdminModel->insertUser([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminController->insertData()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-23 16:26:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 16:26:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-10-23 17:00:42 --> ParseError: syntax error, unexpected token "public"
[Method: GET, Route: user/home]
in APPPATH\Controllers\UserController.php on line 15.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\capas.com\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:01:35 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "user/create_questions.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/create_questions.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/create_questions', [], true)
 3 APPPATH\Controllers\UserController.php(14): view('user/create_questions')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:04:10 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "user/create_questions.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/create_questions.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/create_questions', [], true)
 3 APPPATH\Controllers\UserController.php(14): view('user/create_questions')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:04:19 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "create_questions.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('create_questions.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('create_questions', [], true)
 3 APPPATH\Controllers\UserController.php(14): view('create_questions')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:04:50 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "create_questions.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('create_questions.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('create_questions', [], true)
 3 APPPATH\Controllers\UserController.php(14): view('create_questions')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:05:02 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "accions/templates/CreateQuestionsTemplate/headerTemplate.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('accions/templates/CreateQuestionsTemplate/headerTemplate.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('accions/templates/CreateQuestionsTemplate/headerTemplate', [], true)
 3 APPPATH\Views\user\create_questions.php(2): view('accions/templates/CreateQuestionsTemplate/headerTemplate')
 4 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\capas.com\\app\\Views\\user\\create_questions.php')
 5 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/create_questions', [], true)
 7 APPPATH\Controllers\UserController.php(14): view('user/create_questions')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:05:04 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "accions/templates/CreateQuestionsTemplate/headerTemplate.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('accions/templates/CreateQuestionsTemplate/headerTemplate.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('accions/templates/CreateQuestionsTemplate/headerTemplate', [], true)
 3 APPPATH\Views\user\create_questions.php(2): view('accions/templates/CreateQuestionsTemplate/headerTemplate')
 4 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\capas.com\\app\\Views\\user\\create_questions.php')
 5 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/create_questions', [], true)
 7 APPPATH\Controllers\UserController.php(14): view('user/create_questions')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:05:06 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "accions/templates/CreateQuestionsTemplate/headerTemplate.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('accions/templates/CreateQuestionsTemplate/headerTemplate.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('accions/templates/CreateQuestionsTemplate/headerTemplate', [], true)
 3 APPPATH\Views\user\create_questions.php(2): view('accions/templates/CreateQuestionsTemplate/headerTemplate')
 4 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\capas.com\\app\\Views\\user\\create_questions.php')
 5 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/create_questions', [], true)
 7 APPPATH\Controllers\UserController.php(14): view('user/create_questions')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 17:05:28 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "user/templates/CreateQuestionsTemplate/headerTemplate.php"
[Method: GET, Route: user/createQuestion]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/templates/CreateQuestionsTemplate/headerTemplate.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/templates/CreateQuestionsTemplate/headerTemplate', [], true)
 3 APPPATH\Views\user\create_questions.php(2): view('user/templates/CreateQuestionsTemplate/headerTemplate')
 4 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\capas.com\\app\\Views\\user\\create_questions.php')
 5 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('user/create_questions', [], true)
 7 APPPATH\Controllers\UserController.php(14): view('user/create_questions')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->createQuestion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 18:24:26 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_audit` FOREIGN KEY (`fk_audit`) REFERENCES `audit` (`id_audit`)) in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `qu...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `qu...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `qu...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `qu...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capas.com\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capas.com\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capas.com\app\Controllers\AccionsController.php(125): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 18:24:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_audit` FOREIGN KEY (`fk_audit`) REFERENCES `audit` (`id_audit`))
[Method: POST, Route: accions/insertQuestions]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (:question:, :create_at:, :update_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AccionsController.php(125): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 18:24:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_audit` FOREIGN KEY (`fk_audit`) REFERENCES `audit` (`id_audit`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:24:26\', \'2024-10-23 18:24:26\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:24:26\', \'2024-10-23 18:24:26\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (:question:, :create_at:, :update_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AccionsController.php(125): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 18:24:26 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_audit` FOREIGN KEY (`fk_audit`) REFERENCES `audit` (`id_audit`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:24:26\', \'2024-10-23 18:24:26\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:24:26\', \'2024-10-23 18:24:26\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:24:26\', \'2024-10-23 18:24:26\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (:question:, :create_at:, :update_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AccionsController.php(125): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-23 18:25:03 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_category` FOREIGN KEY (`fk_category`) REFERENCES `category` (`id_category`)) in C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\capas.com\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `qu...', 0)
#1 C:\laragon\www\capas.com\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `qu...')
#2 C:\laragon\www\capas.com\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `qu...')
#3 C:\laragon\www\capas.com\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `qu...', Array, false)
#4 C:\laragon\www\capas.com\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\capas.com\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\capas.com\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\capas.com\app\Controllers\AccionsController.php(125): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\capas.com\system\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
#9 C:\laragon\www\capas.com\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
#10 C:\laragon\www\capas.com\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\capas.com\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\capas.com\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\capas.com\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-23 18:25:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_category` FOREIGN KEY (`fk_category`) REFERENCES `category` (`id_category`))
[Method: POST, Route: accions/insertQuestions]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (:question:, :create_at:, :update_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\AccionsController.php(125): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 18:25:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_category` FOREIGN KEY (`fk_category`) REFERENCES `category` (`id_category`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:25:03\', \'2024-10-23 18:25:03\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:25:03\', \'2024-10-23 18:25:03\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (:question:, :create_at:, :update_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\AccionsController.php(125): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 18:25:03 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`auditoria_capas`.`questions`, CONSTRAINT `fk_category` FOREIGN KEY (`fk_category`) REFERENCES `category` (`id_category`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:25:03\', \'2024-10-23 18:25:03\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:25:03\', \'2024-10-23 18:25:03\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (\'jjj\', \'2024-10-23 18:25:03\', \'2024-10-23 18:25:03\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `questions` (`question`, `create_at`, `update_at`) VALUES (:question:, :create_at:, :update_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AccionsController.php(125): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-23 18:37:03 --> TypeError: preg_match_all(): Argument #2 ($subject) must be of type string, int given
[Method: POST, Route: accions/insertQuestions]
in SYSTEMPATH\HTTP\RequestTrait.php on line 293.
 1 SYSTEMPATH\HTTP\RequestTrait.php(293): preg_match_all('/(?:^[^\\[]+)|\\[[^]]*\\]/', 0, null)
 2 SYSTEMPATH\HTTP\IncomingRequest.php(714): CodeIgniter\HTTP\Request->fetchGlobal('post', 0, 516, 0)
 3 APPPATH\Controllers\AccionsController.php(120): CodeIgniter\HTTP\IncomingRequest->getPost(0)
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AccionsController->insertQuestions()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AccionsController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-10-23 21:23:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 21:23:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 21:29:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 21:29:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 21:29:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 21:31:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-10-23 21:32:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
